## Measure Of Dispersion

In [ ]:
##variance

ages_lst=[23,43,23,56,74,32,68,98,45,32]

In [ ]:
import numpy as np

In [ ]:
mean=np.mean(ages_lst)

In [ ]:
mean

49.4

In [ ]:
var=np.var(ages_lst)
var

541.64

In [ ]:
std=np.std(ages_lst)
std

23.273160507331188

In [ ]:
import pandas as pd

In [ ]:
data=[[10,12,13],[34,23,45],[32,34,21]]
data

[[10, 12, 13], [34, 23, 45], [32, 34, 21]]

In [ ]:
df=pd.DataFrame(data,columns=["A","B","C"])
df

    A   B   C
0  10  12  13
1  34  23  45
2  32  34  21

In [ ]:
df.var()

A    177.333333
B    121.000000
C    277.333333
dtype: float64

In [ ]:
## Row wise
df.var(axis=1)

0      2.333333
1    121.000000
2     49.000000
dtype: float64

In [ ]:
## coulmnwise
df.var(axis=0)

A    177.333333
B    121.000000
C    277.333333
dtype: float64

In [2]:
import seaborn as sns

In [4]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [9]:
df =  sns.load_dataset('healthexp')

In [10]:
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [12]:
df.cov()

<ipython-input-12-6f98a29763d5>:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.cov()

                         Year  Spending_USD  Life_Expectancy
Year               201.098848  2.571883e+04        41.915454
Spending_USD     25718.827373  4.817761e+06      4166.800912
Life_Expectancy     41.915454  4.166801e+03        10.733902

In [17]:
df.corr(method = 'spearman')

<ipython-input-17-6ff71a1c8ea1>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr(method = 'spearman')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000